# 配置dev环境
spring:
  profiles: dev
  application:
    name: aqmsc-eurekaServer-config

server:
  port: 8100
eureka:
  instance:
    hostname: eureka8100.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8100.com:8100/eureka


# 配置test环境
spring:
  profiles: test
  application:
    name: aqmsc-eurekaServer-config

server:
  port: 8200
eureka:
  instance:
    hostname: eureka8200.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8200.com:8200/eureka
