# 配置dev环境
server:
  port: 8084
spring:
  profiles: dev
  application:
    name: aqmsc-provider-depart # 指定当前微服务对外暴露的名称
  # 配置spring data jpa
  jpa:
    # 指定是否在spring容器启动时创建表，默认false
    generate-ddl: true
    # 指定是否在控制台显示sql语句，默认false
    show-sql: true
    # 指定应用重启时不更新表结构
    hibernate:
      ddl-auto: none

    # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.117:3306/test01?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456
# 配置日志
logging:
  pattern:
    # 控制日志在控制台输出的格式
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.aq.provider.reposity: debug
eureka:
  client:
    service-url:
      defaultZone: http://eureka8100:8100/eureka # 指定eureka服务中心
  instance:
    instance-id: aq-msc-provider-8084 # 指定当前客户端在服务注册中心的名字

# 配置test环境
server:
  port: 8085
spring:
  profiles: test
  application:
    name: aqmsc-provider-depart # 指定当前微服务对外暴露的名称
  # 配置spring data jpa
  jpa:
    # 指定是否在spring容器启动时创建表，默认false
    generate-ddl: true
    # 指定是否在控制台显示sql语句，默认false
    show-sql: true
    # 指定应用重启时不更新表结构
    hibernate:
      ddl-auto: none

    # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.117:3306/test02?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456
# 配置日志
logging:
  pattern:
    # 控制日志在控制台输出的格式
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.aq.provider.reposity: debug
eureka:
  client:
    service-url:
      defaultZone: http://eureka8200:8200/eureka # 指定eureka服务中心
  instance:
    instance-id: aq-msc-provider-8085 # 指定当前客户端在服务注册中心的名字